@RolePlayingGame.Api_HostAddress = https://localhost:7279

###################################################################
###  GET – Lista inicial (deve estar vazia no primeiro uso)
###################################################################
GET {{RolePlayingGame.Api_HostAddress}}/characters/
Accept: application/json
###